# Meta
description: hhaze.github.io
keywords: hhaze, jhgu, 블로구

# Author
author_avatar: /img/avatar.png

# Search
search: 
  enable: false
  service: hexo # google/algolia/azure
  # google 
  google_api_key: 
  google_engine_id: 
  # algolia
  algolia_app_id: 
  algolia_api_key: 
  algolia_index_name: 
  # azure
  azure_service_name: 
  azure_index_name: 
  azure_query_key: 

# Miscellaneous
google_analytics: UA-131535785-1
# favicon: /favicon.png

# Less
less:
  compress: true

# Comment
disqus_shortname: hhaze
valine:
  enable: false
  appid:
  appkey:
  notify: false
  verify: false
  placeholder: Just go go
  avatar: retro
  guest_info: nick,mail,link
  pageSize: 10
  visitor: false

# use url, not username
social:
- name: feed
	url: /atom.xml
- name: mail
  url: mailto:jhgu.dev@gmail.com
- name: github
  url: https://github.com/hhaze
- name: twitter
  url: 
- name: google
  url: 
- name: facebook
  url: 
- name: linkedin
  url: 
- name: weibo
  url: 
- name: tumblr
  url: 
- name: dribbble
  url: 
- name: pinterest
  url: 
- name: instagram
  url: 
- name: behance
  url: 
